falcosidekick:
  config:
    webhook:
      address: http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/example
      customHeaders: Falcon:true\,Stuff:yes
  enabled: true

customRules:
  # Applications which are expected to communicate with the Kubernetes API
  rules_user_known_k8s_api_callers.yaml: |-
    - macro: user_known_contact_k8s_api_server_activities
      condition: >
        (container.image.repository = "gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink") or
        (container.image.repository = "quay.io/nissessenap/poddeleter") or (container.image.repository = "argoproj/sensor")
